baseURL = "https://aroseinbloom.com"
languageCode = "en-us"
title = "A Rose in Bloom"
url = "https://emmarosenblatt.com"
[params]
description = "Emma Rosenblatt - LA-based Photographer & Yoga Instructor"
designer = "Briana Gude"
email = "emma.rosenblatt@gmail.com"
instagram = "https://www.instagram.com/a.roseinbloom/"
keywords = ["holiday photographer", "family photographer", "celebrity yoga teacher", "private yoga", "yoga photographer", "dance photographer ", "yoga teacher los angeles", "private yoga teacher", "event photographer ", "best LA photographer", "headshot photographer", "portrait photographer ", "los angeles photographer", "photographer", "yoga", "los angeles", "LA", "portraits", "lifestyle", "occasions"]
logo = "/img/logo.png"
[params.author]
name = "Emma Rosenblatt"
title = "Photographer & Yoga Instructor"
