baseURL = "http://example.org/"
languageCode = "en-us"
title = "A Rose in Bloom"
[params]
  designer = "Briana Gude"
  logo = "/img/logo.png"
  keywords = ["photographer", "yoga", "los angeles", "LA", "portraits", "lifestyle", "occasions"]
  description = "Emma Rosenblatt - LA-based Photographer & Yoga Instructor"
  [params.author]
    name = "Emma Rosenblatt"
    title = "Photographer & Yoga Instructor"
